server:
  port : 8081
  
  
  security:
    oauth2:
     client:
     grantType: client_credentials
     clientId: client-service
     clientSecret: secret
     accessTokenUri: http://localhost:8080/oauth/token
  
